@startuml
'https://plantuml.com/class-diagram


interface  Subject  {
void request()
}

class RealSubject{
void request()
}
class Proxy{
Proxy(Subject)
void request()
void before()
void after()
}

class Client{
void main(String[])
}



Subject <|.. RealSubject
Subject "1" <|--* "1" Proxy
RealSubject<..Client
Proxy<..Client


@enduml